// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_users_gen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID    `json:"id"`
	Email       string       `json:"email"`
	Password    string       `json:"password"`
	FullName    string       `json:"full_name"`
	Role        string       `json:"role"`
	IsActive    bool         `json:"is_active"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}
