// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_users_gen

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
