services:
  db_kios:
    image: postgres:15-alpine
    container_name: db_kios_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL" , "pg_isready -U super_admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  migrate-user:
    build: 
      context: .
      dockerfile: user-service/Dockerfile.migration
    container_name: migrate_user_service
    volumes:
      - ./user-service/db/migrations:/migrations
    env_file:
      - ${ENV_FILE:-.env.development}
    command: up
    depends_on:
      db_kios:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user_service_container
    ports:
      - "8080:8080"
    env_file:
      - ${ENV_FILE:-.env.development}
    environment:
      - SERVICE_NAME=user-service
    depends_on:
      migrate-user:
        condition: service_completed_successfully

volumes:
  postgres_data:
