version: '3.8'

services:
  db_kios:
    image: postgres:15-alpine
    container_name: db_kios_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user_service_app
    ports:
      - "8080:8080"
    env_file:
      - ${ENV_FILE:-.env.development}
    environment:
      - SERVICE_NAME=user-service
      - DB_NAME=db_users
    depends_on:
      - db_kios

volumes:
  postgres_data:
